version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env.local
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
    labels:
      app: web-stream
volumes:
  web-stream-app:
